name: ci-dgraph-net-e2e-tests

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    branches:
      - master
  schedule:
    - cron: "0 0 * * *" # run workflow daily

defaults:
  run:
    working-directory: source/Dgraph.tests.e2e

jobs:
  dotnet-e2e-tests:
    name: dotnet-e2e-tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Spin up Dgraph
        run: |
          docker pull dgraph/standalone:latest
          docker run --name dgraph -d -p "8080:8080" -p "9080:9080" dgraph/standalone:latest

      - name: dotnet restore
        run: dotnet restore

      - name: dotnet build
        run: dotnet build --configuration Release --no-restore

      - name: dotnet run
        run: dotnet run --no-restore
