name: ci-dgraph-net-tests

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    branches:
      - master
  schedule:
    - cron: "0 0 * * *" # run workflow daily

jobs:
  dotnet-tests:
    name: dotnet-tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Dgraph.net
        uses: actions/checkout@v4

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal
